export const SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
};

export const SEVERITY_META = {
  [SEVERITY.LOW]: {
    label: 'Düşük',
    badgeLabel: 'DÜŞÜK',
    labelEn: 'Low',
    color: '#267A3E',
    bg: '#E5F0E2',
    border: '#C5DEC1',
    pillBg: '#DDF5E4',
    pillText: '#267A3E',
    pillBorder: '#B8E3C8',
    description: 'Bilgilendirme amaçlı, operasyonu doğrudan etkilemez.',
    descColor: '#3B7C4E',
    cardBg: '#ECF9EF',
    cardBorder: '#CFEBD6',
    headerTitle: '#3B7C4E',
  },
  [SEVERITY.MEDIUM]: {
    label: 'Orta',
    badgeLabel: 'ORTA',
    labelEn: 'Medium',
    color: '#B07820',
    bg: '#FBEFD6',
    border: '#F0D9A8',
    pillBg: '#FEF3D9',
    pillText: '#B07820',
    pillBorder: '#F0D9A8',
    description: 'Planlamayı etkileyebilir, dikkate alınmalıdır.',
    descColor: '#8B6914',
    cardBg: '#FFF9EE',
    cardBorder: '#F5E6CF',
    headerTitle: '#9A6B22',
  },
  [SEVERITY.HIGH]: {
    label: 'Yüksek',
    badgeLabel: 'YÜKSEK',
    labelEn: 'High',
    color: '#C53030',
    bg: '#F6DCDC',
    border: '#E8B8B8',
    pillBg: '#FDE8E8',
    pillText: '#C53030',
    pillBorder: '#F5C4C4',
    description: 'Uçuş emniyetini doğrudan etkileyebilir.',
    descColor: '#A84848',
    cardBg: '#FDF2F2',
    cardBorder: '#EFD0D0',
    headerTitle: '#A84848',
  },
};

export const HIGH_KEYWORDS = [
  'CLSD',
  'CLOSED',
  'RWY',
  'ILS U/S',
  'AD CLSD',
  'FUEL NOT AVBL',
  'U/S',
  'PROHIB',
  'INOP',
  'PAPI',
  'VASI',
];

export const MEDIUM_KEYWORDS = ['WIP', 'CRANE', 'TWY', 'LIGHTS', 'OBST', 'KITE'];
